version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shipment-tool
    restart: unless-stopped
    networks:
      network1:
    ports:
      - "${PORT:-9066}:9066"
    environment:
      - NODE_ENV=production
      - PORT=9066
      - API_PREFIX=${API_PREFIX:-/api/v1}
      - TRUST_PROXY=${TRUST_PROXY:-loopback, linklocal, uniquelocal}
      # Captcha Services
      - CAPTCHA_SOLVER_API_KEY=${CAPTCHA_SOLVER_API_KEY:-}
      # Google AI
      - GEMINI_API_KEY=${GEMINI_API_KEY:-}
      # Browserless
      - BROWSERLESS_API_TOKEN=${BROWSERLESS_API_TOKEN:-}
      # Api key for accessing the API
      - X_API_KEY=${X_API_KEY:-}
      # Proxy list for browser contexts
      - PROXY_LIST=${PROXY_LIST:-}

networks:
  automation-net:
    driver: bridge
  network1:
    name: dokploy-network
    external: true